//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var Currency = &struct {
	Lei postgres.StringExpression
	Eur postgres.StringExpression
	Usd postgres.StringExpression
}{
	Lei: postgres.NewEnumValue("LEI"),
	Eur: postgres.NewEnumValue("EUR"),
	Usd: postgres.NewEnumValue("USD"),
}
