//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var Metatype = &struct {
	Text   postgres.StringExpression
	Number postgres.StringExpression
	Select postgres.StringExpression
	Bool   postgres.StringExpression
	Date   postgres.StringExpression
	Time   postgres.StringExpression
}{
	Text:   postgres.NewEnumValue("TEXT"),
	Number: postgres.NewEnumValue("NUMBER"),
	Select: postgres.NewEnumValue("SELECT"),
	Bool:   postgres.NewEnumValue("BOOL"),
	Date:   postgres.NewEnumValue("DATE"),
	Time:   postgres.NewEnumValue("TIME"),
}
