//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Applications struct {
	ID      int32 `sql:"primary_key"`
	Owner   int32
	Name    string
	Key     string
	Enabled *bool
	Created time.Time
}
