//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Chats struct {
	ID           int32 `sql:"primary_key"`
	Title        string
	Context      *string
	Reference    *int32
	Participants string
	Archived     string
	Deleted      string
	CreatedAt    time.Time
}
