//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Messages struct {
	ID        int32 `sql:"primary_key"`
	Chat      int32
	From      int32
	Message   string
	Seen      *string
	CreatedAt time.Time
}
