//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type MetaProps struct {
	ID          int32 `sql:"primary_key"`
	Name        string
	Title       string
	Group       *string
	Sort        *int32
	Required    *bool
	Template    *string
	Description *string
	Help        *string
	Type        Metatype
	Options     *string
	Microdata   *string
}
