//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Notifications struct {
	ID       int32 `sql:"primary_key"`
	Owner    int32
	Variant  string
	Title    string
	Contents *string
	Href     *string
	Actions  *string
	Seen     *time.Time
	Created  time.Time
}
