//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type Role string

const (
	Role_Root      Role = "root"
	Role_Admin     Role = "admin"
	Role_Moderator Role = "moderator"
	Role_User      Role = "user"
)

var RoleAllValues = []Role{
	Role_Root,
	Role_Admin,
	Role_Moderator,
	Role_User,
}

func (e *Role) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "root":
		*e = Role_Root
	case "admin":
		*e = Role_Admin
	case "moderator":
		*e = Role_Moderator
	case "user":
		*e = Role_User
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for Role enum")
	}

	return nil
}

func (e Role) String() string {
	return string(e)
}
