//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Seo struct {
	ID          int32 `sql:"primary_key"`
	URI         string
	Title       string
	Description string
	Keywords    string
	Image       string
	UpdatedAt   time.Time
}
