//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Transactions struct {
	ID       int32 `sql:"primary_key"`
	Owner    int32
	AdID     int32
	AdCycle  int32
	AdFrom   *time.Time
	AdTo     *time.Time
	Amount   *float64
	Created  time.Time
	Approved time.Time
}
