//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Users struct {
	ID                   int32 `sql:"primary_key"`
	Email                string
	Password             *string
	GivenName            string
	FamilyName           string
	Phone                *string
	City                 *int32
	Picture              *string
	Source               *string
	Role                 *Role
	Preferences          *string
	ThirdParyAccessToken *string
	EmailActivationToken *string
	PhoneActivationToken *string
	CreatedAt            time.Time
	EmailActivatedAt     *time.Time
	PhoneActivatedAt     *time.Time
}
