services:
  database:
    image: 'postgres:latest'
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: aham
      POSTGRES_PASSWORD: aham
      POSTGRES_DB: aham
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  redis:
    image: redis/redis-stack:latest
    container_name: cdndb
    restart: always
    ports:
      - 6379:6379
    volumes:
      - cdndb:/root/redis
    environment:
      - REDIS_USER=aham
      - REDIS_PASSWORD=aham
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
  wpdb:
    image: mysql:8.0
    restart: always
    container_name: wpdb
    environment:
      MYSQL_DATABASE: aham
      MYSQL_USER: aham
      MYSQL_PASSWORD: aham
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ../data/db/wp:/var/lib/mysql
  wp:
    image: 'wordpress:latest'
    container_name: wp
    ports:
      - 8082:80
    environment:
      WORDPRESS_DB_HOST: wpdb
      WORDPRESS_DB_USER: aham
      WORDPRESS_DB_PASSWORD: aham
      WORDPRESS_DB_NAME: aham
      WORDPRESS_TABLE_PREFIX: aham_
      WORDPRESS_DEBUG: 1
    volumes:
      - ../data/wp:/var/www/html
volumes:
  cdndb:
    external: false

networks:
  aham:
    driver: bridge