services:
  db:
    image: 'postgres:latest'
    container_name: aham_dev_db
    environment:
      POSTGRES_USER: aham
      POSTGRES_PASSWORD: aham
      POSTGRES_DB: aham
    restart: always
    ports:
      - 15432:5432
    volumes:
      - ../../db:/docker-entrypoint-initdb.d
      - ../../../data/db/api:/var/lib/postgresql/data
  redis:
    image: redis/redis-stack:latest
    container_name: aham_dev_redis
    restart: always
    ports:
      - 16379:6379
    environment:
      - REDIS_USER=aham
      - REDIS_PASSWORD=aham
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    volumes:
      - ../../../data/db/redis:/data
networks:
  aham:
    driver: bridge
