services:
  db:
    image: 'postgres:latest'
    container_name: aham_dev_db
    environment:
      POSTGRES_USER: aham
      POSTGRES_PASSWORD: aham
      POSTGRES_DB: aham
    restart: always
    ports:
      - 15432:5432
    volumes:
      - ../../db/api:/docker-entrypoint-initdb.d
  metrics:
    image: 'timescale/timescaledb:latest-pg15'
    container_name: aham_dev_metrics
    environment:
      POSTGRES_USER: aham
      POSTGRES_PASSWORD: aham
      POSTGRES_DB: aham
    restart: always
    ports:
      - 15433:5432
    volumes:
      - ../../db/metrics:/docker-entrypoint-initdb.d
      - ../../../data/db/metrics:/var/lib/postgresql/data
networks:
  aham:
    driver: bridge
