services:
  db:
    image: 'postgres:latest'
    container_name: aham_dev_db
    environment:
      POSTGRES_USER: aham
      POSTGRES_PASSWORD: aham
      POSTGRES_DB: aham
    restart: always
    ports:
      - 15432:5432
    volumes:
      - ../../db/api:/docker-entrypoint-initdb.d
networks:
  aham:
    driver: bridge
