services:
  web:
    image: 'cosminalbu/aham:web'
    container_name: aham_prod_web
    ports:
      - 8080:3000
    environment:
      LISTEN: :8080
    restart: always
    depends_on:
      api:
        restart: true
        condition: service_started
      cdn:
        restart: true
        condition: service_started
    networks:
      aham:
        ipv4_address: 10.5.0.5
  api:
    image: 'cosminalbu/aham:api'
    container_name: aham_prod_api
    ports:
      - 8081:8081
    restart: always
    environment:    
      LISTEN: :8081
      TEMPLATES: /templates
      SMTP_PASSWORD: "@defender@"
      DB: postgres://aham:aham@10.5.0.8:5432/aham
      CDN: http://10.5.0.7:8082
    volumes:
      - /usr/local/aham/gcm/templates:/templates
    depends_on:
      db:
        restart: true
        condition: service_started
      cdn:
        restart: true
        condition: service_started
    networks:
      aham:
        ipv4_address: 10.5.0.6
  cdn:
    image: 'cosminalbu/aham:cdn'
    container_name: aham_prod_cdn
    ports:
      - 8082:8082
    restart: always
    environment:
      LISTEN: :8082
      FILES: /var/aham/cdn
      CERT: /certs/fullchain.pem
      KEY: /certs/privkey.pem
    volumes:
      - /var/aham/cdn:/var/aham/cdn
      - /etc/letsencrypt/live/cdn.aham.ro/:/certs/
    networks:
      aham:
        ipv4_address: 10.5.0.7
  db:
    image: 'postgres:latest'
    container_name: aham_prod_db
    environment:
      POSTGRES_USER: aham
      POSTGRES_PASSWORD: aham
      POSTGRES_DB: aham
    restart: always
    volumes:
      - ../../db/api:/docker-entrypoint-initdb.d
      - /var/aham/db/api:/var/lib/postgresql/data
    networks:
      aham:
        ipv4_address: 10.5.0.8
  wpdb:
    image: mysql:8.0
    restart: always
    container_name: aham_prod_wp_db
    environment:
      MYSQL_DATABASE: aham
      MYSQL_USER: aham
      MYSQL_PASSWORD: aham
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - /var/aham/db/wp:/var/lib/mysql
    networks:
      aham:
        ipv4_address: 10.5.0.10
  wp:
    image: 'wordpress:latest'
    container_name: aham_prod_wp
    restart: always
    ports:
      - 8083:80
    environment:
      WORDPRESS_DB_HOST: 10.5.0.10
      WORDPRESS_DB_USER: aham
      WORDPRESS_DB_PASSWORD: aham
      WORDPRESS_DB_NAME: aham
      WORDPRESS_TABLE_PREFIX: aham_
      WORDPRESS_DEBUG: 0
      WORDPRESS_CONFIG_EXTRA: |
          define('WP_HOME', 'https://blog.aham.ro');
          define('WP_SITEURL', 'https://blog.aham.ro');
    volumes:
      - ../../../wp/theme/aham:/var/www/html/wp-content/themes/aham
      - /var/aham/wp/uploads:/var/www/html/wp-content/uploads
    networks:
      aham:
        ipv4_address: 10.5.0.11
  poste:
    image: analogic/poste.io
    container_name: aham_prod_poste
    restart: always
    hostname: mail.aham.ro
    ports:
      - 25:25
      - 8084:8080
      - 110:110
      - 143:143
      - 465:465
      - 587:587
      - 993:993
      - 995:995
    environment:
      TZ: Europe/Bucharest
      HTTPS: OFF
      HTTP_PORT: 8080
    volumes:
      - /var/aham/mail:/data
    networks:
      aham:
        ipv4_address: 10.5.0.12
  url:
    image: 'cosminalbu/aham:url'
    container_name: aham_prod_url
    ports:
      - 8085:8085
    restart: always
    environment:
      LISTEN: :8085
      DOMAIN: https://url.aham.ro
      DBPATH: /var/aham/db/url
    volumes:
      - /var/aham/db/url:/var/aham/db/url
    networks:
      aham:
        ipv4_address: 10.5.0.13
networks:
  aham:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
