services:
  web:
    image: 'cosminalbu/aham:web'
    container_name: aham_prod_web
    ports:
      - 8080:3000
    environment:
      LISTEN: :8080
    depends_on:
      api:
        restart: true
        condition: service_started
      cdn:
        restart: true
        condition: service_started
    networks:
      aham:
        ipv4_address: 10.5.0.5
  api:
    image: 'cosminalbu/aham:api'
    container_name: aham_prod_api
    ports:
      - 8081:8081
    environment:    
      LISTEN: :8081
      DB: postgres://aham:aham@10.5.0.8:5432/aham
      CDN: https://10.5.0.7:8082
    depends_on:
      db:
        restart: true
        condition: service_started
      cdn:
        restart: true
        condition: service_started
    networks:
      aham:
        ipv4_address: 10.5.0.6
  cdn:
    image: 'cosminalbu/aham:cdn'
    container_name: aham_prod_cdn
    ports:
      - 8082:8082
    environment:
      LISTEN: :8082
      FILES: /usr/local/cdn
      REDIS: redis://:aham@10.5.0.9:6379/0?protocol=3
    volumes:
      - ../../../data/cdn:/usr/local/cdn
    depends_on:
      redis:
        restart: true
        condition: service_started
    networks:
      aham:
        ipv4_address: 10.5.0.7
  db:
    image: 'postgres:latest'
    container_name: aham_prod_db
    environment:
      POSTGRES_USER: aham
      POSTGRES_PASSWORD: aham
      POSTGRES_DB: aham
    volumes:
      - ../../db:/docker-entrypoint-initdb.d
      - ../../../data/db/api:/var/lib/postgresql/data
    networks:
      aham:
        ipv4_address: 10.5.0.8
  redis:
    image: redis/redis-stack:latest
    container_name: aham_prod_redis
    restart: always
    environment:
      - REDIS_USER=aham
      - REDIS_PASSWORD=aham
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    volumes:
      - ../../../data/db/redis:/data
    networks:
      aham:
        ipv4_address: 10.5.0.9
networks:
  aham:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1