services:
  database:
    image: 'postgres:latest'
    container_name: db-test
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: aham
      POSTGRES_PASSWORD: aham
      POSTGRES_DB: aham
    volumes:
      - ./db:/docker-entrypoint-initdb.d
networks:
  aham:
    driver: bridge