//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Ads = Ads.FromSchema(schema)
	Balance = Balance.FromSchema(schema)
	Categories = Categories.FromSchema(schema)
	Chats = Chats.FromSchema(schema)
	Cities = Cities.FromSchema(schema)
	Counties = Counties.FromSchema(schema)
	Favourites = Favourites.FromSchema(schema)
	Messages = Messages.FromSchema(schema)
	MetaAssign = MetaAssign.FromSchema(schema)
	MetaProps = MetaProps.FromSchema(schema)
	Notifications = Notifications.FromSchema(schema)
	Reports = Reports.FromSchema(schema)
	Resources = Resources.FromSchema(schema)
	Sam = Sam.FromSchema(schema)
	Seo = Seo.FromSchema(schema)
	Templates = Templates.FromSchema(schema)
	Transactions = Transactions.FromSchema(schema)
	Users = Users.FromSchema(schema)
}
