services:
  database:
    image: 'postgres:latest'
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: aham
      POSTGRES_PASSWORD: aham
      POSTGRES_DB: aham
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  redis:
    image: redis/redis-stack:latest
    container_name: cdndb
    restart: always
    ports:
      - 6379:6379
    volumes:
      - cdndb:/root/redis
    environment:
      - REDIS_USER=aham
      - REDIS_PASSWORD=aham
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

volumes:
  cdndb:
    external: false

networks:
  aham:
    driver: bridge