name: Test backend services

on:
  push:
    branches: [ "main" ]
    branches-ignore:
      - '**'
  pull_request:
    branches: [ "main" ]
    branches-ignore:
      - '**'

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.5'

    - name: Test
      run: make test
