name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: Build
      working-directory: backend/service/cdn
      run: go build -v ./... -o ../../../../bin/cdn

    - name: Test
      working-directory: backend/service/cdn
      run: go test -v ./...
