name: Build and test web app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '23.6.0'

    - name: Install
      run: cd web && npm install
    - name: Lint
      run: cd web && npm run lint
    - name: Build
      run: cd web && npm install && npm run build
    - name: Test Chrome
      run: cd web && npm run e2e:chrome
    - name: Test Firefox
      run: cd web && npm run e2e:firefox
